/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "compute.h"

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->operator1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->operator2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->is_prime))
		 return FALSE;
	return TRUE;
}
