/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPUTE_H_RPCGEN
#define _COMPUTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct response {
	long operator1;
	long operator2;
	int is_prime;
};
typedef struct response response;

#define COMPUTE_PROG 123456789
#define COMPUTE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define compute 1
extern  response * compute_1(long *, CLIENT *);
extern  response * compute_1_svc(long *, struct svc_req *);
extern int compute_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define compute 1
extern  response * compute_1();
extern  response * compute_1_svc();
extern int compute_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_response (XDR *, response*);

#else /* K&R C */
extern bool_t xdr_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMPUTE_H_RPCGEN */
